#!/bin/bash

echo "=========================="echo "
echo ""
echo "Step 1: Open Xcode"
echo "  Command: open SpotFinder.xcodeproj"
echo ""
echo "Step 2: Add files to project"
 Right-click 'SpotFinder' folder in Project Navigator"echo "  
 Select 'Add Files to SpotFinder...'"echo "  
 Select folders: Models, Services, ViewModels, Views, Utilities"echo "  
 Check 'Copy items if needed'"echo "  
 Click 'Add'"echo "  
echo ""
echo "Step 3: Delete ContentView.swift"
 Move to Trash"
echo ""
echo "Step 4: Build and Run"
 Select iOS 17+ simulator"echo "  
 Press Cmd + R"echo "  
echo ""
 SETUP_GUIDE.md"echo "  echo "
 README.md"echo "  
 API_DOCUMENTATION.md"echo "  
echo ""
echo "Ready? Press Enter to open Xcode..."
read
open SpotFinder.xcodeproj
